include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - avoid_print
    - prefer_single_quotes
    - sort_child_properties_last
    - use_super_parameters

analyzer:
  errors:
    dangling_library_doc_comments: ignore 