name: api_client
description: Pulse 앱의 API 통합 레이어
version: 0.1.0

publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  # 프로젝트 내부 패키지
  core:
    path: ../core
  # API 및 HTTP
  dio: 5.3.3
  retrofit: ^4.4.2
  # 상태 관리
  riverpod: 2.4.0
  flutter_riverpod: 2.4.0
  # 인증
  supabase_flutter: ^2.9.0
  # 캐싱
  shared_preferences: ^2.5.3
  # 유틸리티
  logger: 2.0.2
  json_annotation: 4.8.1
  riverpod_annotation: ^2.1.5
  fpdart: ^1.1.1
  envied: ^1.1.1
  http: ^1.3.0
  path: ^1.9.1
  meta: ^1.16.0
  freezed_annotation: 2.4.1
  connectivity_plus: ^6.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  # 코드 생성
  build_runner: ^2.4.15
  retrofit_generator: ^9.1.9
  json_serializable: 6.7.1
  # 린트 및 분석
  flutter_lints: ^5.0.0
  riverpod_generator: ^2.3.2
  freezed: ^2.5.3
  envied_generator: ^1.1.1
  mocktail: ^1.0.4

flutter:
  # 필요한 Flutter 설정 추가 