version: '3.8'

services:
  crawler-api:
    build: .
    container_name: pulse-crawler-api
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    restart: unless-stopped
