name: core
description: 공유 모델 및 유틸리티를 포함하는 코어 패키지
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  # 모델 생성 및 직렬화
  freezed_annotation: 2.4.1
  json_annotation: 4.8.1
  uuid: 4.1.0
  # 유틸리티
  intl: 0.18.1
  logger: 2.0.2
  # 네트워크 및 API
  dio: 5.3.3
  # 상태 관리
  riverpod: 2.4.0
  flutter_riverpod: 2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  # 코드 생성
  build_runner: 2.4.15
  freezed: 2.4.2
  json_serializable: 6.7.1
  # 린트 및 분석
  flutter_lints: 2.0.3
  
flutter:
  # 필요한 Flutter 설정 추가 